// Generated by CoffeeScript 1.4.0
(function() {

  (function() {
    var imgPlaceholder,
      _this = this;
    imgPlaceholder = (function() {

      imgPlaceholder.prototype.imgs = [];

      imgPlaceholder.prototype.imgWidth = 0;

      imgPlaceholder.prototype.imgHeight = 0;

      imgPlaceholder.prototype.imgColor = '888';

      imgPlaceholder.prototype.imgBGColor = 'DDD';

      imgPlaceholder.prototype.imgAlt = '';

      imgPlaceholder.prototype.imgFormats = ['jpg', 'jpeg', 'png', 'gif'];

      function imgPlaceholder() {
        this.imgs = document.getElementsByTagName('img');
        this.placeholder(this.imgs);
      }

      imgPlaceholder.prototype.placeholder = function(imgs) {
        var canvas, img, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = imgs.length; _i < _len; _i++) {
          img = imgs[_i];
          if (!this.valide(img)) {
            continue;
          }
          this.parse(img.src);
          console.log(this.imgWidth, this.imgHeight, this.imgBGColor, this.imgColor, this.imgAlt);
          canvas = this.createCanvas(this.imgWidth, this.imgHeight);
          _results.push(img.src = canvas.toDataURL());
        }
        return _results;
      };

      imgPlaceholder.prototype.createCanvas = function(width, height) {
        var canvas, canvasContext;
        if (width == null) {
          width = 300;
        }
        if (height == null) {
          height = 150;
        }
        canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        canvasContext = canvas.getContext('2d');
        canvasContext.fillStyle = this.imgBGColor;
        canvasContext.fillRect(0, 0, width, height);
        canvasContext.fillStyle = this.imgColor;
        canvasContext.font = "" + (width / 10) + "px Arial";
        canvasContext.fillText(this.imgAlt, width / 3.3, height / 2);
        return canvas;
      };

      imgPlaceholder.prototype.valide = function(img) {
        var format, strEndsWith, _i, _len, _ref;
        if (img.src === '') {
          return false;
        }
        if (img.src === window.location.href) {
          return false;
        }
        strEndsWith = function(str, end) {
          return str.indexOf(end, str.length - end.length) !== -1;
        };
        _ref = this.imgFormats;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          format = _ref[_i];
          if (strEndsWith(img.src, format)) {
            return false;
          }
        }
        return true;
      };

      imgPlaceholder.prototype.parse = function(str) {
        var sets, size, sizeStr, _ref;
        sets = str.split('#');
        sizeStr = sets[0].split('/').pop();
        size = sizeStr.split('x');
        if (size[0]) {
          this.imgWidth = size[0];
        }
        if (size[1]) {
          this.imgHeight = size[1];
        }
        if (sets[1]) {
          this.imgBGColor = sets[1];
        }
        if (sets[2]) {
          this.imgColor = sets[2];
        }
        return this.imgAlt = (_ref = sets[3]) != null ? _ref : sizeStr;
      };

      return imgPlaceholder;

    })();
    return document.addEventListener('DOMContentLoaded', function() {
      return new imgPlaceholder();
    });
  })();

}).call(this);
