// Generated by CoffeeScript 1.4.0
(function() {

  (function() {
    var imgPlaceholder,
      _this = this;
    imgPlaceholder = (function() {

      imgPlaceholder.prototype.imgs = [];

      imgPlaceholder.prototype.imgWidth = 0;

      imgPlaceholder.prototype.imgHeight = 0;

      imgPlaceholder.prototype.imgColor = '#888';

      imgPlaceholder.prototype.imgBGColor = '#DDD';

      imgPlaceholder.prototype.imgAlt = '';

      imgPlaceholder.prototype.imgFormats = ['jpg', 'jpeg', 'png', 'gif'];

      function imgPlaceholder() {
        this.imgs = document.getElementsByTagName('img');
        this.placeholder(this.imgs);
      }

      imgPlaceholder.prototype.placeholder = function(imgs) {
        var img, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = imgs.length; _i < _len; _i++) {
          img = imgs[_i];
          if (!this.valide(img)) {
            continue;
          }
          this.parse(img.attributes.placeholder.value);
          _results.push(img.src = this.createCanvas().toDataURL());
        }
        return _results;
      };

      imgPlaceholder.prototype.createCanvas = function() {
        var canvas, canvasContext;
        canvas = document.createElement('canvas');
        canvas.width = this.imgWidth;
        canvas.height = this.imgHeight;
        canvasContext = canvas.getContext('2d');
        canvasContext.fillStyle = this.imgBGColor;
        canvasContext.fillRect(0, 0, this.imgWidth, this.imgHeight);
        canvasContext.fillStyle = this.imgColor;
        canvasContext.font = "" + (this.imgWidth / 10) + "px Arial";
        canvasContext.fillText(this.imgAlt, this.imgWidth / 3.3, this.imgHeight / 2);
        return canvas;
      };

      imgPlaceholder.prototype.valide = function(img) {
        if (!img.attributes.placeholder) {
          return false;
        }
        if (img.src && img.src !== window.location.href) {
          return false;
        }
        return true;
      };

      imgPlaceholder.prototype.parse = function(placeholder) {
        var size;
        this.imgAlt = placeholder;
        size = placeholder.split('x');
        this.imgWidth = size[0];
        return this.imgHeight = size[1];
      };

      return imgPlaceholder;

    })();
    return document.addEventListener('DOMContentLoaded', function() {
      return new imgPlaceholder();
    });
  })();

}).call(this);
