// Generated by CoffeeScript 1.4.0
(function() {
  var DOMLoader;

  DOMLoader = (function() {
    var document;

    function DOMLoader() {}

    document = window.document;

    DOMLoader.loaded = false;

    DOMLoader.list = [];

    DOMLoader.init = function() {
      if (this.isLoaded()) {
        this.loaded = true;
      } else {
        this.listenLoad();
      }
      return this;
    };

    DOMLoader.load = function(fn) {
      if (typeof fn !== 'function') {
        return;
      }
      if (this.loaded) {
        return fn();
      }
      return this.list.push(fn);
    };

    DOMLoader.listenLoad = function(fn) {
      if (document.addEventListener) {
        document.addEventListener('DOMContentLoaded', this.onLoad, false);
        return window.addEventListener('load', this.onLoad, false);
      } else {
        document.attachEvent('onreadystatechange', this.onLoad);
        return window.attachEvent('onload', this.onLoad);
      }
    };

    DOMLoader.isLoaded = function() {
      return document.readyState !== "loading";
    };

    DOMLoader.onLoad = function() {
      var fn, _results;
      DOMLoader.loaded = true;
      _results = [];
      while (DOMLoader.list.length) {
        fn = DOMLoader.list.shift();
        _results.push(fn());
      }
      return _results;
    };

    return DOMLoader;

  }).call(this);

  this.DOMLoader = DOMLoader.init();

}).call(this);
